import "./globals.css";
import { RebondFont, SourceSansFont } from "@/utils/fontSources";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${RebondFont.variable} ${SourceSansFont.variable} bg-mirage`}
      >
        {children}
      </body>
    </html>
  );
}
