import "./globals.css";
import { RebondFont, SourceSansFont } from "@/utils/fontSources";
import { Plus_Jakarta_Sans, Meow_Script } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const JakartaSansFont = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta-sans",
});

const MeowFont = Meow_Script({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-meow",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${RebondFont.variable} ${SourceSansFont.variable} ${JakartaSansFont.variable} ${MeowFont.variable} bg-black`}
      >
        {children}
      </body>
    </html>
  );
}
