import "./globals.css";
import { RebondFont, SourceSansFont } from "@/utils/fontSources";
import {
  Plus_Jakarta_Sans,
  Meow_Script,
  JetBrains_Mono,
  Inter_Tight,
  Instrument_Serif,
} from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const JakartaSansFont = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta-sans",
});

const MeowFont = Meow_Script({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-meow",
});

const JetBrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
});

const InterTight = Inter_Tight({
  subsets: ["latin"],
  variable: "--font-inter-tight",
});

const Instrument = Instrument_Serif({
  subsets: ["latin"],
  style: "italic",
  weight: ["400"],
  variable: "--font-instrument-serif",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body
        className={`${RebondFont.variable} ${SourceSansFont.variable} ${JakartaSansFont.variable} ${MeowFont.variable} ${JetBrains.variable} ${InterTight.variable} ${Instrument.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
