export const WorkList = [
  {
    id: "fundednext",
    idx: "01",
    client: "FundedNext · NextVentures",
    industry: "Prop trading · Fintech",
    title: "Scaling a prop-trading platform past its next order of magnitude",
    role: "UX Lead",
    year: "2024 →",
    period: "Ongoing",
    tags: ["Design System", "Revenue UX", "Dashboard"],
    caseUrl: null,
    outcome:
      "Rebuilt purchase funnel & dashboard; established the system that unblocked a 12-person product org.",
    metric: {
      value: "Revenue growth",
      label: "Measurable lift on rebuilt funnel",
    },
    image: "/app-mockup.png",
  },
  {
    id: "starcineplex",
    idx: "02",
    client: "Star Cineplex",
    industry: "Ticketing · Consumer",
    title:
      "A cinema booking experience that finally fits the way people decide",
    role: "Product Designer",
    year: "2022",
    period: "6 months",
    tags: ["Consumer app", "Booking UX", "iOS + Android"],
    caseUrl: null,
    outcome:
      "Re-architected discovery-to-seat-select in three screens. Made showtimes legible, seat maps native, and payment a decision, not a form.",
    metric: { value: "3 screens", label: "From browse to booked" },
    image: "/app-mockup.png",
  },
  {
    id: "othership",
    idx: "03",
    client: "Othership",
    industry: "SaaS · Hybrid work",
    title: "Giving hybrid teams a shared place to work, anywhere",
    role: "Product Designer",
    year: "2021",
    period: "18 months",
    tags: ["SaaS", "Marketplace", "Mobile + Web"],
    caseUrl: "/case-study/othership",
    outcome:
      "Designed the core booking and team coordination flows now used across multiple global markets. Reduced discovery-to-confirmed-desk to three taps.",
    metric: { value: "3 taps", label: "To a confirmed booking" },
    image: "/app-mockup.png",
  },
  {
    id: "banking",
    idx: "04",
    client: "Basic Bank · NRB Bank",
    industry: "Retail banking",
    title: "Sustainable banking for customers who inherit paper habits",
    role: "Sr. UX Designer",
    year: "2021",
    period: "One year",
    tags: ["Banking", "Research", "Accessibility"],
    caseUrl: null,
    outcome:
      "Redesigned account opening, transfers, and statements for two national banks. Worked within regulatory constraints to ship interfaces that read the same on a feature phone as on a flagship.",
    metric: {
      value: "2 banks",
      label: "Shipped against regulatory constraint",
    },
    image: "/app-mockup.png",
  },
];
